services:
  web:
    build:
      context: ./web 
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - app

  app:
    build:
      context: ./server 
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    env_file:
      - ./server/.env
    depends_on:
      bd:
        condition: service_healthy

  bd:
    image: bitnami/postgresql:17.5.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=brevly
    volumes:
      - "./docker:/docker-entrypoint-initdb.d"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker -d brevly"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  docker:
