/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShortUrlRouteImport } from './routes/$shortUrl'
import { Route as IndexRouteImport } from './routes/index'

const ShortUrlRoute = ShortUrlRouteImport.update({
  id: '/$shortUrl',
  path: '/$shortUrl',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$shortUrl': typeof ShortUrlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$shortUrl': typeof ShortUrlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$shortUrl': typeof ShortUrlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$shortUrl'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$shortUrl'
  id: '__root__' | '/' | '/$shortUrl'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShortUrlRoute: typeof ShortUrlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$shortUrl': {
      id: '/$shortUrl'
      path: '/$shortUrl'
      fullPath: '/$shortUrl'
      preLoaderRoute: typeof ShortUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShortUrlRoute: ShortUrlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
